const INITIAL_STATE = 'INITIAL_STATE'
const INITIAL_AREA = 'INITIAL_AREA'
const UPDATE_AREA = 'UPDATE_AREA'
const INITIAL_MAP = 'INITIAL_MAP'
const UPDATE_MAP_TYPE = 'UPDATE_MAP_TYPE'
const UPDATE_MAP_EDIT = 'UPDATE_MAP_EDIT'
const UPDATE_MAP_HIGHPONIT = 'UPDATE_MAP_HIGHPONIT'
const UPDATE_MAP_EDIT_LEVEL = 'UPDATE_MAP_EDIT_LEVEL'
const UPDATE_MAP_EDIT_TYPE = 'UPDATE_MAP_EDIT_TYPE'
const UPDATE_MAP_EDIT_LOCATION = 'UPDATE_MAP_EDIT_LOCATION'

export {
  INITIAL_STATE,
  INITIAL_AREA,
  UPDATE_AREA,
  INITIAL_MAP,
  UPDATE_MAP_TYPE,
  UPDATE_MAP_EDIT,
  UPDATE_MAP_HIGHPONIT,
  UPDATE_MAP_EDIT_LEVEL,
  UPDATE_MAP_EDIT_TYPE,
  UPDATE_MAP_EDIT_LOCATION
}
